[package]
name = "t3-chat-clone-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
db = { path = "./db" }
serde = "1.0.219"
anyhow = "1.0.98"
async-openai = "0.28.3"
